export const IMAGES_LOAD_PROGRESS = 'IMAGES_LOAD_PROGRESS';
export const IMAGES_LOAD_SUCCESS = 'IMAGES_LOAD_SUCCESS';
export const IMAGES_LOAD_FAIL = 'IMAGES_LOAD_FAIL';

export const IMAGES_STAT_PROGRESS = 'IMAGES_STAT_PROGRESS';
export const IMAGES_STAT_SUCCESS = 'IMAGES_STAT_SUCCESS';
export const IMAGES_STAT_FAIL = 'IMAGES_STAT_FAIL';
